### ISSUE TITLE
Help running test-uniswap-liquidity.js

### ISSUE THREAD

**Issue by ssadek1976** [t4sk/defi-by-example#20]
Concerning a tutorial video that I came across around adding/removing liquidity into Uniswap https://www.youtube.com/watch?v=816kTTNzcHs, I have the following the issue.

When I attempt to run test-uniswap-liquidity.js under truffle environment, it keeps failing on this line of code:

`await tokenA.transfer(CALLER, TOKEN_A_AMOUNT, { from: TOKEN_A_WHALE });`

_truffle(mainnet_fork)> truffle test test/test-uniswap-liquidity.js --network mainnet_fork
Using network 'mainnet_fork'.

Compiling your contracts...
Compiling https://github.com/OpenZeppelin\contracts\token\ERC20\IERC20.sol
Compiling https://github.com/OpenZeppelin\contracts\utils\math\SafeMath.sol
Compiling .\contracts\Flashloan-arbitrage.sol
Compiling .\contracts\Migrations.sol
Compiling .\contracts\TestUniswapLiquidity.sol
Compiling .\contracts\UniswapV2Library.sol
Compiling .\contracts\interfaces\IERC20.sol
Compiling .\contracts\interfaces\IUniswapV2Callee.sol
Compiling .\contracts\interfaces\IUniswapV2Factory.sol
Compiling .\contracts\interfaces\IUniswapV2Pair.sol
Compiling .\contracts\interfaces\IUniswapV2Router01.sol
Compiling .\contracts\interfaces\IUniswapV2Router02.sol
Compiling .\contracts\interfaces\Uniswap.sol
Artifacts written to C:\Users\SAMUEL~1.SAD\AppData\Local\Temp\test--17744-7ubcxUBqpENh
Compiled successfully using:

solc: 0.8.16+commit.07a7930e.Emscripten.clang
step1...
step2...
step4...TOKEN_A_AMOUNT = BN {
negative: 0,
words: [ 779264, 149, <1 empty item> ],
length: 2,
red: null
}
step4...TOKEN_B_AMOUNT = BN {
negative: 0,
words: [ 779264, 149, <1 empty item> ],
length: 2,
red: null
}
Contract: TestUniswapLiquidity
CALLER... 0x031213df405840b7BCdEb5A7A9126BbD77A6aed3
step6...contract: 0xa0A14ceC4C0cFa67a3d5f39A4704465fC2e446B1
step7 - sent Ether...
step8a - CALLER: 0x031213df405840b7BCdEb5A7A9126BbD77A6aed3
step8b - TOKEN_A_AMOUNT (parsed): 10000000000
step8c - TOKEN_B_AMOUNT (parsed): 10000000000
calling again CALLER... 0x031213df405840b7BCdEb5A7A9126BbD77A6aed3
TOKEN_A_WHALE: 0xee2826453A4Fd5AfeB7ceffeEF3fFA2320081268
1) "before each" hook for "add liquidity and remove liquidity"

0 passing (2s)
1 failing

Contract: TestUniswapLiquidity
"before each" hook for "add liquidity and remove liquidity":
**Error: Returned error: sender account not recognized** -- Reason given: Custom error (could not decode).
at Context. (test\test-uniswap-liquidity.js:48:18)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
truffle(mainnet_fork)> truffle --version
Truffle v5.5.28 (core: 5.5.28)
Ganache v7.4.0
Solidity - 0.8.16 (solc-js)
Node v16.17.0
Web3.js v1.7.4_

I would greatly appreciate any insights as to how I could resolve this problem which has been going on for several days now.

One other thing, the liquidity concept is only applicable for non-flash swap contracts/transactions, is that correct?
Reason being, I attempted to run a flash swap loan arbitrage app in truffle that I´ve developed but keeps giving me with the **Insufficient liquidity** error message which was the original reason why I came across your video.

Thanks once again for your help.

BR,
Samuel

**Comment by ssadek1976** [comment]
Tried running `ganache-cli --secure -u 0 --fork https://mainnet.infura.io/v3/XXX` to see if it rectifies the problem but still coming up with the same error

**Comment by t4sk** [comment]
```
"before each" hook for "add liquidity and remove liquidity":
Error: Returned error: sender account not recognized
```

Run mainnet fork
Make sure you've unlocked the correct accounts

**Comment by ssadek1976** [comment]
Yes but I have already done via the window prompt command `ganache-cli --secure -u 0 --fork https://mainnet.infura.io/v3/XXX`

**Comment by t4sk** [comment]
Test is setup to unlock specific accounts. Because at the time I created the test, those accounts had the amount of tokens required for the test. 

To fix your test, you need to unlock an account that has the tokens required in the test

**Comment by ssadek1976** [comment]
Yes I can see quite a few of WHALE tokens. Did you create these yourself?
Which tokens would you suggest for me to use that I could add into one of my accounts in my test and the code to perform this, please.

BR

Sent from my iPhone

On 8 Sep 2022, at 08:14, Taz ***@***.***> wrote:

﻿

Test is setup to unlock specific accounts. Because at the time I created the test, those accounts had the amount of tokens required for the test.

To fix your test, you need to unlock an account that has the tokens required in the test

**Comment by ssadek1976** [comment]
When I launch local Ganache to fork off mainnet, it comes with 10 accounts containing 1000 ETH balances, could I use and unlock one of these for my test then?


________________________________

**Comment by ssadek1976** [comment]
Are these accounts or tokens?

--unlock $WETH_WHALE \
--unlock $DAI_WHALE \
--unlock $USDC_WHALE \
--unlock $USDT_WHALE \
--unlock $WBTC_WHALE \

If tokens could I use these in local Ganache accounts in the testuniswapflash code example that you have?


________________________________

**Comment by ssadek1976** [comment]
Hi Taz,

One question pls, in test-uniswap-flash-swap.js, is the WHALE address that you specified in that script contained the USDC tokens used for the test i.e. specified USDC token address in variable TOKEN_BORROW?

It´s driving me mad.

Thank you very much!

De: ***@***.***>
Enviado: jueves, 8 de septiembre de 2022 8:14
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [t4sk/defi-by-example] Help running test-uniswap-liquidity.js (Issue #20)


Test is setup to unlock specific accounts. Because at the time I created the test, those accounts had the amount of tokens required for the test.

To fix your test, you need to unlock an account that has the tokens required in the test

**Comment by ssadek1976** [comment]
Reason I asked is because I used RinkeBy ETH (RETH) token address from RinkeBy testnet and the bal is still to zero.


De: Samuel ***@***.***>
Enviado: viernes, 9 de septiembre de 2022 16:23
Para: ***@***.***>; ***@***.***>; Dhiraj ***@***.***>
CC: ***@***.***>
Asunto: RE: [t4sk/defi-by-example] Help running test-uniswap-liquidity.js (Issue #20)

The code snippet referred to below questions:

const BN = require("bn.js")
const { sendEther, pow } = require("./util")
const { DAI, DAI_WHALE, USDC, USDC_WHALE, USDT, USDT_WHALE } = require("./config")

const IERC20 = artifacts.require("IERC20")
const TestUniswapFlashSwap = artifacts.require("TestUniswapFlashSwap")

contract("TestUniswapFlashSwap", (accounts) => {
 const WHALE = USDC_WHALE
 const TOKEN_BORROW = USDC
 const DECIMALS = 6
 const FUND_AMOUNT = pow(10, DECIMALS).mul(new BN(2000000))
 const BORROW_AMOUNT = pow(10, DECIMALS).mul(new BN(1000000))

 let testUniswapFlashSwap
 let token
 beforeEach(async () => {
    token = await IERC20.at(TOKEN_BORROW)
    testUniswapFlashSwap = await TestUniswapFlashSwap.new()

    await sendEther(web3, accounts[0], WHALE, 1)

    // send enough token to cover fee
    const bal = await token.balanceOf(WHALE)
    assert(bal.gte(FUND_AMOUNT), "balance < FUND")
    await token.transfer(testUniswapFlashSwap.address, FUND_AMOUNT, {
      from: WHALE,
    })
 })

 it("flash swap", async () => {
    const tx = await testUniswapFlashSwap.testFlashSwap(token.address, BORROW_AMOUNT, {
      from: WHALE,
    })

    for (const log of tx.logs) {
      console.log(log.args.message, log.args.val.toString())
    }
 })
})


De: Samuel ***@***.***>
Enviado: viernes, 9 de septiembre de 2022 16:21
Para: ***@***.***>; ***@***.***>
CC: ***@***.***>
Asunto: RE: [t4sk/defi-by-example] Help running test-uniswap-liquidity.js (Issue #20)


Hi Taz,

One question pls, in test-uniswap-flash-swap.js, is the WHALE address that you specified in that script contained the USDC tokens used for the test i.e. specified USDC token address in variable TOKEN_BORROW?

It´s driving me mad.

Thank you very much!

De: ***@***.***>
Enviado: jueves, 8 de septiembre de 2022 8:14
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [t4sk/defi-by-example] Help running test-uniswap-liquidity.js (Issue #20)


Test is setup to unlock specific accounts. Because at the time I created the test, those accounts had the amount of tokens required for the test.

To fix your test, you need to unlock an account that has the tokens required in the test

**Comment by Samboy76** [comment]
The code snippet referred to below questions:

const BN = require("bn.js")
const { sendEther, pow } = require("./util")
const { DAI, DAI_WHALE, USDC, USDC_WHALE, USDT, USDT_WHALE } = require("./config")

const IERC20 = artifacts.require("IERC20")
const TestUniswapFlashSwap = artifacts.require("TestUniswapFlashSwap")

contract("TestUniswapFlashSwap", (accounts) => {
 const WHALE = USDC_WHALE
 const TOKEN_BORROW = USDC
 const DECIMALS = 6
 const FUND_AMOUNT = pow(10, DECIMALS).mul(new BN(2000000))
 const BORROW_AMOUNT = pow(10, DECIMALS).mul(new BN(1000000))

 let testUniswapFlashSwap
 let token
 beforeEach(async () => {
    token = await IERC20.at(TOKEN_BORROW)
    testUniswapFlashSwap = await TestUniswapFlashSwap.new()

    await sendEther(web3, accounts[0], WHALE, 1)

    // send enough token to cover fee
    const bal = await token.balanceOf(WHALE)
    assert(bal.gte(FUND_AMOUNT), "balance < FUND")
    await token.transfer(testUniswapFlashSwap.address, FUND_AMOUNT, {
      from: WHALE,
    })
 })

 it("flash swap", async () => {
    const tx = await testUniswapFlashSwap.testFlashSwap(token.address, BORROW_AMOUNT, {
      from: WHALE,
    })

    for (const log of tx.logs) {
      console.log(log.args.message, log.args.val.toString())
    }
 })
})


De: Samuel ***@***.***>
Enviado: viernes, 9 de septiembre de 2022 16:21
Para: ***@***.***>; ***@***.***>
CC: ***@***.***>
Asunto: RE: [t4sk/defi-by-example] Help running test-uniswap-liquidity.js (Issue #20)


Hi Taz,

One question pls, in test-uniswap-flash-swap.js, is the WHALE address that you specified in that script contained the USDC tokens used for the test i.e. specified USDC token address in variable TOKEN_BORROW?

It´s driving me mad.

Thank you very much!

De: ***@***.***>
Enviado: jueves, 8 de septiembre de 2022 8:14
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [t4sk/defi-by-example] Help running test-uniswap-liquidity.js (Issue #20)


Test is setup to unlock specific accounts. Because at the time I created the test, those accounts had the amount of tokens required for the test.

To fix your test, you need to unlock an account that has the tokens required in the test
